version: '2'
services:
    sidagoimport1-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/sidagoImport1/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=sidagoImport1
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
